spring:
  application.name: prices
  datasource:
    url: jdbc:h2:mem:prices
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true
  jpa.hibernate.ddl-auto: none
  flyway:
    baselineOnMigrate: true
    url: jdbc:h2:mem:prices
    user: sa
    password: password
    locations:
      - 'classpath:db/migration'
      - 'classpath:db/data'

springdoc.api-docs.path: /api-docs
#logging.level.root: debug